# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from userinput import User_Input 
from GetID import GetID
import re
import time 
import csv
import requests

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 777)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QPushButton:pressed{background-color: rgb(0, 0, 0); }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 160, 1131, 531))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_friend = QtWidgets.QWidget()
        self.tab_friend.setObjectName("tab_friend")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.tab_friend)
        self.tableWidget_1.setGeometry(QtCore.QRect(-10, 1, 1131, 501))
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(9)
        self.tableWidget_1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(8, item)
        self.tabWidget.addTab(self.tab_friend, "")
        self.tab_memGroup = QtWidgets.QWidget()
        self.tab_memGroup.setObjectName("tab_memGroup")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_memGroup)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 1131, 501))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(9)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        self.tabWidget.addTab(self.tab_memGroup, "")
        self.tab_cmt = QtWidgets.QWidget()
        self.tab_cmt.setObjectName("tab_cmt")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_cmt)
        self.tableWidget_3.setGeometry(QtCore.QRect(-10, 0, 1131, 501))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(9)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        self.tabWidget.addTab(self.tab_cmt, "")
        self.tab_likePost = QtWidgets.QWidget()
        self.tab_likePost.setObjectName("tab_likePost")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_likePost)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 0, 1131, 501))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(9)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(8, item)
        self.tabWidget.addTab(self.tab_likePost, "")
        self.tab_postUser = QtWidgets.QWidget()
        self.tab_postUser.setObjectName("tab_postUser")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_postUser)
        self.tableWidget_5.setGeometry(QtCore.QRect(-10, 0, 1131, 461))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(6)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        self.label = QtWidgets.QLabel(self.tab_postUser)
        self.label.setGeometry(QtCore.QRect(900, 480, 121, 16))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.tab_postUser)
        self.textEdit.setGeometry(QtCore.QRect(1030, 470, 71, 31))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_postUser, "")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setObjectName("tab_info")
        self.tabWidget.addTab(self.tab_info, "")
        self.btnLogout = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogout.setGeometry(QtCore.QRect(900, 80, 201, 28))
        self.btnLogout.setObjectName("btnLogout")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 700, 851, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn1UID = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.btn1UID.setFont(font)
        self.btn1UID.setObjectName("btn1UID")
        self.horizontalLayout.addWidget(self.btn1UID)
        self.btnUID = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnUID.setObjectName("btnUID")
        self.horizontalLayout.addWidget(self.btnUID)
        self.btnSave_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnSave_2.setObjectName("btnSave_2")
        self.horizontalLayout.addWidget(self.btnSave_2)
        self.btnDel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnDel.setObjectName("btnDel")
        self.horizontalLayout.addWidget(self.btnDel)
        self.btnCheck = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnCheck.setObjectName("btnCheck")
        self.horizontalLayout.addWidget(self.btnCheck)
        self.btnPause = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnPause.setObjectName("btnPause")
        self.horizontalLayout.addWidget(self.btnPause)
        self.txtToken = QtWidgets.QTextEdit(self.centralwidget)
        self.txtToken.setGeometry(QtCore.QRect(0, 80, 651, 31))
        self.txtToken.setPlaceholderText("")
        self.txtToken.setObjectName("txtToken")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(680, 80, 111, 31))
        self.btnSave.setObjectName("btnSave")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tools Facebook"))
        item = self.tableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.tableWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "UID"))
        item = self.tableWidget_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.tableWidget_1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Birthday"))
        item = self.tableWidget_1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Age Ranger"))
        item = self.tableWidget_1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget_1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Phone"))
        item = self.tableWidget_1.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Location"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_friend), _translate("MainWindow", "Bạn Bè UID"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "UID"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Birthday"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Age Ranger"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Phone"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Location"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_memGroup), _translate("MainWindow", "Thành Viên Nhóm"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "UID"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Birthday"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Age Ranger"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Phone"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Location"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cmt), _translate("MainWindow", "Binh luận Bài viết"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "UID"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Birthday"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Age Ranger"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget_4.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Phone"))
        item = self.tableWidget_4.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Location"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_likePost), _translate("MainWindow", "Like Bài Viết"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nội Dung"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Like"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Comment"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Share"))
        self.label.setText(_translate("MainWindow", "Số lượng bài viết:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_postUser), _translate("MainWindow", "Quét bài Viết /User"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_info), _translate("MainWindow", "Thông Tin"))
        self.btnLogout.setText(_translate("MainWindow", "Đăng Xuất"))
        self.btn1UID.setText(_translate("MainWindow", "QUÉT UID"))
        self.btnUID.setText(_translate("MainWindow", "QUÉT TỆP UID"))
        self.btnSave_2.setText(_translate("MainWindow", "LƯU DANH SÁCH"))
        self.btnDel.setText(_translate("MainWindow", "XÓA DANH SÁCH"))
        self.btnCheck.setText(_translate("MainWindow", "LỌC TRÙNG"))
        self.btnPause.setText(_translate("MainWindow", "DỪNG"))
        self.txtToken.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
        self.sukien()
        # self.sukien()
    def load_QTable(self,data,tab):
        # tab ={0:self.tableWidget_1,1:self.tableWidget_2,2:self.tableWidget_3,3:self.tableWidget_4,3:self.tableWidget_5}
        for row_number,data_row in enumerate(data):
            tab.insertRow(row_number)
            for col_number,value in enumerate(data_row):
                tab.setItem(row_number,col_number,QtWidgets.QTableWidgetItem(str(value)))
    def show_input_user(self):
        tab ={0:self.tableWidget_1,1:self.tableWidget_2,2:self.tableWidget_3,3:self.tableWidget_4,4:self.tableWidget_5}
        # if self.userinput is None:
        current = self.tabWidget.currentIndex()
        self.userinput = QtWidgets.QDialog()
        self.userinput.ui = User_Input()
        self.userinput.ui.setupUi(self.userinput)
        self.userinput.exec_()
        text =self.userinput.ui.text
        dataID=re.findall(r'[0-9a-zA-Z]+',text)
        # print(dataID)
        try:
            if text!='':
                # print(text)
                if current==0:
                    for uid in dataID:
                        MainWindow.ui.GetID.get_all_friends_user(uid,tab[current])
                        # self.load_QTable(data,tab[current])
                if current==1:
                    for uid in dataID:
                        data = MainWindow.ui.GetID.get_all_members_group(uid)
                        self.load_QTable(data,tab[current])
                if current==2:
                    for uid in dataID:
                        data = MainWindow.ui.GetID.get_all_user_comment_post(uid)
                        self.load_QTable(data,tab[current])
                if current==3:
                    for uid in dataID:
                        data = MainWindow.ui.GetID.get_all_user_like_post(uid)
                        self.load_QTable(data,tab[current])
                if current==4:
                    for uid in dataID:
                        limit = re.match(r'[0-9]+',self.textEdit.toPlainText()).group()
                        data = MainWindow.ui.GetID.get_post_from_page_user(uid,limit)
                        self.load_QTable(data,tab[current])
        except :
            self.show_error('Kiểm tra lại Token hoặc UID của bạn')
            print('Error')

    def sukien(self):
        # self.userinput=None
        self.btn1UID.clicked.connect(self.show_input_user)
        self.btnUID.clicked.connect(self.show_input_user)
        self.btnSave_2.clicked.connect(self.save_data)
        self.btnSave.clicked.connect(self.save_token)
        self.load_token()
        self.btnDel.clicked.connect(self.delete_table)
        self.txtToken.setPlaceholderText('Nhập token ở đây')
        self.progress = QtWidgets.QProgressBar()
        self.progress.setGeometry(200, 80, 250, 20)
    def save_data(self):
        tab ={0:self.tableWidget_1,1:self.tableWidget_2,2:self.tableWidget_3,3:self.tableWidget_4,4:self.tableWidget_5}
        current = self.tabWidget.currentIndex()
        self.handleSave(tab[current])
    def handleSave(self,table):
        path = QtWidgets.QFileDialog.getSaveFileName(None, 'Save File', '', 'CSV(*.csv)')
        path=path[0]+'.csv'
        if path!='':
            print(path)
            with open(path, 'w') as stream:
                writer = csv.writer(stream)
                for row in range(table.rowCount()):
                    rowdata = []
                    for column in range(table.columnCount()):
                        item = table.item(row, column)
                        if item is not None:
                            # print(str(item.text()))
                            rowdata.append(str(item.text()))
                        else:
                            rowdata.append('')
                    writer.writerow(rowdata)
    def load_token(self):
        with open('tk.txt','r+') as f:
            token = f.read()
        print(token)
        if token!='':
            self.txtToken.setText(token)
            MainWindow.ui.GetID.update_token(token)
    def save_token(self):
        token = str(re.search(r'[0-9a-zA-Z]+',self.txtToken.toPlainText()).group())
        if token!='':
            MainWindow.ui.GetID.update_token(token)
            r = requests.get('http://danhngdz.pythonanywhere.com/token/?token='+str(token))
            print(r)
            with open('tk.txt','w') as f:
                f.write(token)
        print(MainWindow.ui.GetID.accessToken)
    def delete_table(self):
        tab ={0:self.tableWidget_1,1:self.tableWidget_2,2:self.tableWidget_3,3:self.tableWidget_4,4:self.tableWidget_5}
        current= self.tabWidget.currentIndex()
        tab[current].setRowCount(0)
    def show_error(self,mess):
        QtWidgets.QMessageBox.about(MainWindow,'Error',mess)
def get_friend():
    begin = time.time()
    ob = GetID("EAAAAUaZA8jlABAJCGmz5jXILm66IkQNZArr7jTaaL4ZBxwiAcgqumKZAI8znD7fzmcVlg4ZBD0RgIubup86JvPAvU5yOLthWQQNq6tIJDTnxL6QH5Tx7EKiqz5OaFY1U7N9ZClfV7sZBvxYS2pU1jaOExELMLxPHsAZD")
    # data=ob.get_all_members_group(1013427422092872,'data.txt')
    # print(data)
    # ob.get_all_videos_group(1173636692750000,'linkvideos.txt')
    # data= ob.get_all_friends_user('100006122645127','data3.txt')
    # print(data)
    # data=ob.get_all_friends_user(100006122645127,'data2.txt')
    # data =ob.get_all_user_comment_post('1088171441285136','data3.txt')
    # data = ob.get_all_user_like_post('941568386026009')
    data = ob.get_post_from_page_user('548664955331244',10)
    print("Time: {} s".format(time.time()-begin))
    return data

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.ui = Ui_MainWindow()
    MainWindow.ui.GetID = GetID('')
    MainWindow.ui.setupUi(MainWindow)
    MainWindow.show()
    # data =get_friend()
    # ui.load_QTable(data)
    sys.exit(app.exec_())